services:
  postgres:
    image: postgres:15-alpine
    container_name: xmpp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - xmpp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ejabberd:
    image: ejabberd/ecs:latest
    container_name: xmpp_ejabberd
    restart: unless-stopped
    environment:
      # Основные переменные - они переопределят значения в YAML
       EJABBERD_MACRO_HOST: ${DOMAIN}
       EJABBERD_MACRO_ADMIN_JID: ${EJABBERD_ADMIN_JID}
       EJABBERD_MACRO_DB_NAME: ${POSTGRES_DB}
       EJABBERD_MACRO_DB_USER: ${POSTGRES_USER}
       EJABBERD_MACRO_DB_PASS: ${POSTGRES_PASSWORD}
    expose:
      - "5223"             # TCP-порт для клиентских подключений (c2s)
      - "5269"             # TCP-порт для серверных соединений (s2s)
      - "5280"             # HTTP-интерфейс
    ports:
      - "3478:3478/udp" # UDP-порт для STUN/TURN (VoIP, WebRTC)
      - "5349:5349"     # TCP-порт для STUN/TURN с TLS
    volumes:
      - ./data/ejabberd/ssl:/certs:ro
      # - ./data/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/:/certs:ro
      - ./ejabberd/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./data/ejabberd/backup:/home/ejabberd/backup
      - ./data/ejabberd/upload:/home/ejabberd/upload
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - xmpp_network

  php:
    image: php:8.4-fpm-alpine
    container_name: xmpp_php
    restart: unless-stopped
    volumes:
      - ./php:/var/www/html
    networks:
      - xmpp_network

  caddy:
    build: ./caddy/build
    container_name: xmpp_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}   # передаём домен в Caddy для использования в Caddyfile
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./php:/var/www/html
    networks:
      - xmpp_network
    depends_on:
      - php

  coturn:
    image: coturn/coturn:latest
    container_name: xmpp_coturn
    restart: unless-stopped
    network_mode: host
    environment:
      - TURN_USER=${TURN_USER}
      - TURN_PASSWORD=${TURN_PASSWORD}
      - TURN_REALM=${DOMAIN}
      - TURN_SECRET=${TURN_SECRET}
      - TURN_PORT=${TURN_PORT}
      - TURN_TLS_PORT=${TURN_TLS_PORT}
      - TURN_MIN_PORT=${TURN_MIN_PORT}
      - TURN_MAX_PORT=${TURN_MAX_PORT}
      - TURN_VERBOSE=1
    command:
      - -n
      - --user=${TURN_USER}:${TURN_PASSWORD}
      - --realm=${DOMAIN}
      - --static-auth-secret=${TURN_SECRET}
      - --listening-port=${TURN_PORT}
      - --tls-listening-port=${TURN_TLS_PORT}
      - --min-port=${TURN_MIN_PORT}
      - --max-port=${TURN_MAX_PORT}
      - --fingerprint
      - --lt-cred-mech
      - --use-auth-secret
      - --no-tcp-relay
      - --no-tlsv1
      - --no-tlsv1_1
      - --no-sslv3
      - --log-file=stdout

networks:
  xmpp_network:
    driver: bridge